name: Push changes
# The deploy workflow relies on inputs from a call or dispatch
# This deploys to certain environments when specific branches are pushed


on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy to prod
    uses: ./.github/workflows/deploy.yml
    with:
      deployment-env: prod
    secrets: inherit
